import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import { Main, Cite, Pics } from "./sections";
import Main from "./sections/Main";
import Cite from "./sections/Cite";
import Pics from "./sections/Pics";
import CTA from "./sections/CTA";
import FormButton from "./sections/FormButton";

import { useWindowScroll } from "react-use";
import List from "./sections/List";
import Menu from "./sections/Menu";

export default function Home() {
  const { y } = useWindowScroll();

  return (
    <div className={styles.container}>
      <Head>
        <title>Lasciva Lust</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu y={y} />

      <Main y={y} />

      <a name="about" />
      <Cite />

      <a name="gallery" />
      <Pics y={y} />

      <a name="protocol" />
      <List />

      <CTA />
      {/* <section>SESSION</section>

      <section>TESTIMONIALS</section>

      <section>APPLICATION</section> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
